name: ReleaseCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Release to S3
      env:
        AWS_Bucket_Name: ${{secrets.AWS_Bucket_Name}}
        AWS_Access_Key : ${{secrets.AWS_Access_Key}}
        AWS_Access_Secret : ${{secrets.AWS_Access_Secret}}
        AWS_REGION: 'ap-south-1'
        SOURCE_DIR: 'public'

    
